### PR TITLE
add initial links demonstrating what I'm aiming for

### PR DESCRIPTION
**Pull request by bcoe**
My goal is to provide a list of resources that:

1. help a developer write code that is likely to work on Windows.
2. help developers debug their software on Windows.
3. help developers wire up their software to Windows CI., so that they don't have regressions.

Feedback welcome, is there a better name for this list? CC: @sindresorhus

### CODE REVIEW

**Comment by bcoe** [comment]
I'm quite open to renaming, or changing the categories -- I'd just love to provide a resource somewhere that helps Node.js developers better write cross-platform libraries.

**Comment by sindresorhus** [comment]
Maybe `Cross-platform Node.js`?

-

Might also be worth co-operating with https://github.com/Microsoft/nodejs-guidelines or at least get a link to your list from there.

**Comment by bcoe** [comment]
@sindresorhus as you suggested, perhaps awesome-nodejs-testing, with a section on Windows testing tools? This could reference the more thorough Microsoft document.

**Comment by sindresorhus** [comment]
@bcoe From your description it sounds like you want not only cover testing, but also how to write cross-platform aware code, like always using `path.join()`, etc. If so, the name `awesome-nodejs-testing` would be too narrow.

**Comment by bcoe** [comment]
@jamestalmage from your experience getting AVA working on AppVeyor, would love your opinion on whether you think this could be a worthwhile list.

Dan you think of some links worth adding?

**Comment by jamestalmage** [comment]
Yes. I think this it is worthwhile.

The only additional thing I can think of is a list of things that are broken on Windows (like streams from forked processes)

**Pull request merged**
