### PR TITLE
add `pkg`

### PR DESCRIPTION
**Pull request by Hongarc**
Support: FreeBSD, Linux, Alpine, MacOS, Win

### CODE REVIEW

**Comment by ehmicky** [comment]
Thanks for this contribution! 

I am wondering whether this fits the scope of this repository. I think the main thing `pkg` (and related tools) provides from a cross-platform standpoint is the ability to distribute to platforms that cannot install Node.js.

But that is more about hardware portability and less about OS portability which has been the scope of this repository so far. For Windows, Mac, Linux (including Alpine) and BSD, Node.js can be easily installed, so using `pkg` does not provide cross-platform benefits.

What do you think? Also I would like to know what @bcoe thinks about this?

**Comment by bcoe** [comment]
@ehmicky I'm on the fence on this one, `pkg` allows you to create binaries that target multiple platforms ... which does seem to fit with this repository. At the same time, maybe we put a stake in the ground, and argue that the tools in this repository are related to writing portable code, not about packaging it?

**Comment by ehmicky** [comment]
From that point of view, I think readers might be interested in the whole development experience, i.e. packaging as well.

Should we re-open it?

There's also [`nexe`](https://github.com/nexe/nexe) that does the same but with a different approach.

**Comment by bcoe** [comment]
@ehmicky I have a slight leaning towards reopening this issue, and perhaps we could add a new sectio called something like "Creating Cross-Platform Binaries"?

**Comment by ehmicky** [comment]
Sounds good. Would simply "Packaging" be more straight-forward?

**Comment by styfle** [comment]
Maybe something like this? https://github.com/styfle/awesome-desktop-js#packaging

**Comment by ehmicky** [comment]
Yes thanks for that link! If there is already a repo for this, I think we should add this link in a "See also" section. And then exclude packaging-related links from this repo?

**Comment by bcoe** [comment]
@ehmicky works for me :+1:

**Comment by ehmicky** [comment]
Sounds good!

We can also remove the link to `electron` as it related to packaging?

**Comment by ehmicky** [comment]
Done in https://github.com/bcoe/awesome-cross-platform-nodejs/commit/60bb06f27c99b359de7382334c8fa90e553564f8

@styfle I've also added you as a [contributor](https://github.com/bcoe/awesome-cross-platform-nodejs#contributing) for this nice link. Thanks!

**Pull request closed without merging**
