### PR TITLE
update link *contributions guidelines*

### PR DESCRIPTION
**Pull request by Hongarc**
Old link: https://github.com/bcoe/awesome-cross-platform-nodejs/blob/master/blob/master/contributing.md

New link: https://github.com/bcoe/awesome-cross-platform-nodejs/blob/master/contributing.md

### CODE REVIEW

**Comment by ehmicky** [comment]
Hum I get different results.

When I open a new issue, then click on "Preview", the link currently points to `https://github.com/bcoe/awesome-cross-platform-nodejs/blob/master/contributing.md`, which is correct.

With this PR, it would point instead to `https://github.com/bcoe/awesome-cross-platform-nodejs/contributing.md` which is invalid.

Am I missing something?

**Comment by ehmicky** [comment]
Looks good now, nice idea. Could you update it in the PR template as well, please?

**Comment by ehmicky** [comment]
Oh wait, I don't think that's working. This link redirects to `https://github.com/contributing.md`.

**Comment by Hongarc** [comment]
I have removed it :)

**Comment by ehmicky** [comment]
Now the issue is that I'm copy/pasting those templates in many GitHub projects. Having different repository names is not ideal for that.

On the other hand, when viewing the template in Markdown (not preview), it's more useful for users to have the full link, so that's more important.

**Comment by ehmicky** [comment]
I have updated the [contributors](https://github.com/bcoe/awesome-cross-platform-nodejs#contributing) list considering all those PRs. Thanks again!

**Comment by Hongarc** [comment]
Thank you very much for the prompt reply.

**Pull request merged**
