### PR TITLE
Don't start the description with A or An

### PR DESCRIPTION
**Pull request by Hongarc**
**A** or **An** is unnecessary

Do you want add `Don't start the description with A or An` to `contributing.md`

### CODE REVIEW

**Comment by ehmicky** [comment]
Thanks @Hongarc!

**Comment by Hongarc** [comment]
@ehmicky Do you want add one more rule `Don't start the description with A or An` to `contributing.md` or `pull_request_template.md`?

**Comment by ehmicky** [comment]
Oops sorry I missed that. Yes that sounds like a good thing to add to `contributing.md`.

**Comment by ehmicky** [comment]
Done in https://github.com/bcoe/awesome-cross-platform-nodejs/commit/4298afea6f1c2b170661a30cc4bc9091250ee1fc.

**Pull request merged**
