### PR TITLE
add `cash` to Shell`

### PR DESCRIPTION
**Pull request by Hongarc**

### CODE REVIEW

**Comment by ehmicky** [comment]
Looks good, thanks! Should this item be right after ShellJS?

**Comment by ehmicky** [comment]
Should it be two separate items instead since the two projects are distinct (although related)?

**Comment by sindresorhus** [comment]
Doesn't look actively maintained. Last commit was in 2017.

**Comment by ehmicky** [comment]
@sindresorhus is correct, sorry I missed it. Thanks for the PR though! However pointing users to unmaintained repositories is not a good idea.

**Pull request closed without merging**
